### PR TITLE
jest Test cases

### PR DESCRIPTION
**Pull request by rohit-ambre**
Added tests with 100% code coverage using jest

Note: install codecov as dev dependency and create account on codecov for coverage report on github.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | yes
| Fixed issues  | #number

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by rohit-ambre** [comment]
github action used `jest` for `npm run test` now, so you can check code coverage in github checks

**Comment by pranavacharya** [comment]
> 
> 
> github action used `jest` for `npm run test` now, so you can check code coverage in github checks

Hi, the test cases looks good, can you make changes in the workflow to include lint and build also. 

Example :

>     # Install, lint, test and build
>     - name: npm install, lint, test and build
>       run: |
>         npm install
>         npm run lint
>         npm test
>         npm run build


Thanks for contributing 👍

**Comment by rohit-ambre** [comment]
modified workflow steps

**Comment by rohit-ambre** [comment]
added test cases for validators

**Comment by pranavacharya** [comment]
Thanks for contributing 👍

**Pull request merged**
